"""
Country & Tax Rules Engine for Capital OS.
Provides localized tax contexts, broker recommendations, and investment rules for 20+ jurisdictions.
"""

from typing import Dict, Any, List

COUNTRY_CONFIGS: Dict[str, Dict[str, Any]] = {
    "UA": {
        "country_name": "Украина 🇺🇦",
        "currency": "UAH",
        "base_fiat_symbol": "₴",
        "capital_gains_tax_rate": 0.18,
        "military_tax_rate": 0.015,
        "total_investment_tax_rate": 0.195,
        "dividend_tax_rate": 0.09,
        "recommended_brokers": ["Interactive Brokers", "Freedom Finance Europe", "Monobank (ОВГЗ)", "Sense Bank"],
        "tax_notes": "Дивиденды по иностранным акциям: 9% + 1.5% военный сбор. Государственные облигации (ОВГЗ) — 0% налогов.",
        "preferred_assets": ["ОВГЗ (Гособлигации)", "Мировые ETF (VWRA/VUAA)", "Высокодоходный кэш"],
    },
    "PL": {
        "country_name": "Польша 🇵🇱",
        "currency": "PLN",
        "base_fiat_symbol": "zł",
        "capital_gains_tax_rate": 0.19,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.19,
        "dividend_tax_rate": 0.19,
        "recommended_brokers": ["XTB", "Interactive Brokers", "mBank", "Bossa"],
        "tax_notes": "Налог Белки (Podatek Belki) 19%. Используйте счета IKE / IKZE для освобождения от налога на прибыль.",
        "preferred_assets": ["IKE/IKZE ETF", "Vanguard FTSE All-World", "Obligacje Skarbowe (Гособлигации)"],
    },
    "US": {
        "country_name": "США 🇺🇸",
        "currency": "USD",
        "base_fiat_symbol": "$",
        "capital_gains_tax_rate": 0.15,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.15,
        "dividend_tax_rate": 0.15,
        "recommended_brokers": ["Vanguard", "Fidelity", "Charles Schwab", "Interactive Brokers"],
        "tax_notes": "Используйте налоговые льготы Roth IRA и 401(k) для безналогового роста капитала.",
        "preferred_assets": ["VTI (Total US)", "VOO (S&P 500)", "BND (Total Bond)", "VT (Total World)"],
    },
    "DE": {
        "country_name": "Германия 🇩🇪",
        "currency": "EUR",
        "base_fiat_symbol": "€",
        "capital_gains_tax_rate": 0.25,
        "military_tax_rate": 0.055,
        "total_investment_tax_rate": 0.26375,
        "dividend_tax_rate": 0.26375,
        "recommended_brokers": ["Scalable Capital", "Trade Republic", "Interactive Brokers", "Comdirect"],
        "tax_notes": "Abgeltungsteuer 25% + Soli. Необлагаемый лимит (Sparerpauschbetrag) €1,000 в год на человека.",
        "preferred_assets": ["Аккумулирующие ETF (VWCE)", "iShares Core S&P 500", "Денежный рынок (XEON)"],
    },
    "UK": {
        "country_name": "Великобритания 🇬🇧",
        "currency": "GBP",
        "base_fiat_symbol": "£",
        "capital_gains_tax_rate": 0.20,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.20,
        "dividend_tax_rate": 0.0875,
        "recommended_brokers": ["Interactive Investor", "Trading 212", "AJ Bell", "Hargreaves Lansdown"],
        "tax_notes": "Stocks & Shares ISA позволяет инвестировать до £20,000 в год с нулевым налогом на прибыль и дивиденды.",
        "preferred_assets": ["ISA Global Equity ETFs", "Vanguard FTSE All-World", "UK Gilts"],
    },
    "CA": {
        "country_name": "Канада 🇨🇦",
        "currency": "CAD",
        "base_fiat_symbol": "C$",
        "capital_gains_tax_rate": 0.15,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.15,
        "dividend_tax_rate": 0.15,
        "recommended_brokers": ["Questrade", "Wealthsimple", "Interactive Brokers Canada"],
        "tax_notes": "Счета TFSA (Tax-Free Savings Account) и RRSP обеспечивают безналоговый рост инвестиций.",
        "preferred_assets": ["VEQT (All-Equity ETF)", "XEQT (Core Equity)", "Vanguard S&P 500"],
    },
    "FR": {
        "country_name": "Франция 🇫🇷",
        "currency": "EUR",
        "base_fiat_symbol": "€",
        "capital_gains_tax_rate": 0.30,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.30,
        "dividend_tax_rate": 0.30,
        "recommended_brokers": ["Boursorama", "Trade Republic", "DEGIRO", "Interactive Brokers"],
        "tax_notes": "PFU (Flat Tax) 30%. План PEA (Plan d'Épargne en Actions) дает освобождение от налога на прибыль через 5 лет.",
        "preferred_assets": ["PEA MSCI World ETF", "Amundi PEA S&P 500", "Livret A"],
    },
    "ES": {
        "country_name": "Испания 🇪🇸",
        "currency": "EUR",
        "base_fiat_symbol": "€",
        "capital_gains_tax_rate": 0.19,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.19,
        "dividend_tax_rate": 0.19,
        "recommended_brokers": ["MyInvestor", "Indexa Capital", "DEGIRO", "Interactive Brokers"],
        "tax_notes": "Трансфер между индексными фондами (Fondos Indexados) не облагается налогом до момента вывода средств.",
        "preferred_assets": ["Vanguard Global Index Fund", "iShares World Equity", "Letras del Tesoro"],
    },
    "IT": {
        "country_name": "Италия 🇮🇹",
        "currency": "EUR",
        "base_fiat_symbol": "€",
        "capital_gains_tax_rate": 0.26,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.26,
        "dividend_tax_rate": 0.26,
        "recommended_brokers": ["Directa", "Fineco", "Trade Republic", "Interactive Brokers"],
        "tax_notes": "Налог на прирост капитала 26%, гособлигации (BTP) облагаются по льготной ставке 12.5%. Планы PIR безналоговые.",
        "preferred_assets": ["ETF UCITS All-World", "BTP Гособлигации", "XEON Liquidity"],
    },
    "CH": {
        "country_name": "Швейцария 🇨🇭",
        "currency": "CHF",
        "base_fiat_symbol": "CHF",
        "capital_gains_tax_rate": 0.0,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.0,
        "dividend_tax_rate": 0.35,
        "recommended_brokers": ["Swissquote", "Interactive Brokers", "Saxo Bank"],
        "tax_notes": "Для частных инвесторов налог на прирост капитала 0%! Налог на дивиденды удерживается по ставке Verrechnungssteuer 35%.",
        "preferred_assets": ["US Accumulating ETFs (VT/VTI)", "Swiss Market Index (SMI)", "Global Equity"],
    },
    "KZ": {
        "country_name": "Казахстан 🇰🇿",
        "currency": "KZT",
        "base_fiat_symbol": "₸",
        "capital_gains_tax_rate": 0.10,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.10,
        "dividend_tax_rate": 0.10,
        "recommended_brokers": ["Freedom Finance Global (МФЦА)", "Halyk Finance", "Interactive Brokers"],
        "tax_notes": "Сделки на биржах KASE и AIX (МФЦА) освобождены от индивидуального подоходного налога.",
        "preferred_assets": ["AIX ETF", "Ноты Нацбанка РК", "Global Index ETFs (IBKR)"],
    },
    "GE": {
        "country_name": "Грузия 🇬🇪",
        "currency": "GEL",
        "base_fiat_symbol": "₾",
        "capital_gains_tax_rate": 0.05,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.05,
        "dividend_tax_rate": 0.05,
        "recommended_brokers": ["Bank of Georgia (Galt & Taggart)", "TBC Capital", "Interactive Brokers"],
        "tax_notes": "Доходы от продажи ценных бумаг при удержании более 2 лет освобождаются от подоходного налога.",
        "preferred_assets": ["Еврооблигации Грузии", "Global Index ETFs", "Депозиты в USD/GEL"],
    },
    "IL": {
        "country_name": "Израиль 🇮🇱",
        "currency": "ILS",
        "base_fiat_symbol": "₪",
        "capital_gains_tax_rate": 0.25,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.25,
        "dividend_tax_rate": 0.25,
        "recommended_brokers": ["Meitav", "Psagot", "Interactive Brokers Israel"],
        "tax_notes": "Реальный налог 25% с поправкой на инфляцию. Программа 'Купат Гемель ле-Ашкаа' дает налоговые льготы при пенсии.",
        "preferred_assets": ["Kupat Gemel", "Индексные фонды TA-125 / S&P 500", "Global ETFs"],
    },
    "AE": {
        "country_name": "ОАЭ 🇦🇪",
        "currency": "AED",
        "base_fiat_symbol": "AED",
        "capital_gains_tax_rate": 0.0,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.0,
        "dividend_tax_rate": 0.0,
        "recommended_brokers": ["Sarwa", "Interactive Brokers (ADGM/DIFC)", "Saxo Bank"],
        "tax_notes": "0% налог на прирост капитала и 0% налог на дивиденды для резидентов-физлиц.",
        "preferred_assets": ["Global Index ETFs (VWRA)", "Sukuk Bonds", "Real Estate REITs"],
    },
    "EE": {
        "country_name": "Эстония 🇪🇪",
        "currency": "EUR",
        "base_fiat_symbol": "€",
        "capital_gains_tax_rate": 0.20,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.20,
        "dividend_tax_rate": 0.20,
        "recommended_brokers": ["LHV Pank", "Swedbank", "Interactive Brokers"],
        "tax_notes": "Инвестиционный счет (Investeerimiskonto) позволяет отложить налог до момента вывода прибыли из системы.",
        "preferred_assets": ["LHV Kasvukonto", "Vanguard All-World ETF", "Балтийские акции"],
    },
    "LT": {
        "country_name": "Литва 🇱🇹",
        "currency": "EUR",
        "base_fiat_symbol": "€",
        "capital_gains_tax_rate": 0.15,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.15,
        "dividend_tax_rate": 0.15,
        "recommended_brokers": ["Swedbank", "SEB", "Interactive Brokers"],
        "tax_notes": "Льгота €500 в год на прибыль от продажи ценных бумаг не облагается налогом (GPM).",
        "preferred_assets": ["Балтийские фонды", "Global Index ETFs (VWCE)", "Гособлигации"],
    },
    "LV": {
        "country_name": "Латвия 🇱🇻",
        "currency": "EUR",
        "base_fiat_symbol": "€",
        "capital_gains_tax_rate": 0.20,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.20,
        "dividend_tax_rate": 0.20,
        "recommended_brokers": ["Indexo", "Swedbank", "Interactive Brokers"],
        "tax_notes": "Инвестиционный счет (Ieguldījumu konts) позволяет реинвестировать прибыль без уплаты налога до закрытия счета.",
        "preferred_assets": ["Indexo 3. līmenis", "iShares Core MSCI World", "Krājobligācijas"],
    },
    "CZ": {
        "country_name": "Чехия 🇨🇿",
        "currency": "CZK",
        "base_fiat_symbol": "Kč",
        "capital_gains_tax_rate": 0.15,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.15,
        "dividend_tax_rate": 0.15,
        "recommended_brokers": ["Portu", "Fio banka", "XTB", "Interactive Brokers"],
        "tax_notes": "Тест времени: при удержании ценных бумаг более 3 лет доход полностью освобождается от налогов (0%).",
        "preferred_assets": ["DIP (Пенсионный инвестпродукт)", "Portu Portfolio", "VWCE ETF"],
    },
    "AT": {
        "country_name": "Австрия 🇦🇹",
        "currency": "EUR",
        "base_fiat_symbol": "€",
        "capital_gains_tax_rate": 0.275,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.275,
        "dividend_tax_rate": 0.275,
        "recommended_brokers": ["Flatex Austria", "DADAT", "Interactive Brokers"],
        "tax_notes": "KESt (Kapitalertragsteuer) 27.5%. Брокеры Steuereinfach автоматически рассчитывают и удерживают налог.",
        "preferred_assets": ["Meldefonds (Аккредитованные ETF)", "Vanguard All-World", "Bundesanleihen"],
    },
    "NL": {
        "country_name": "Нидерланды 🇳🇱",
        "currency": "EUR",
        "base_fiat_symbol": "€",
        "capital_gains_tax_rate": 0.36,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.36,
        "dividend_tax_rate": 0.15,
        "recommended_brokers": ["DEGIRO", "Interactive Brokers", "ABN AMRO", "Brand New Day"],
        "tax_notes": "Система Box 3 с необлагаемым базовым лимитом €57,000 на человека (€114,000 для партнеров).",
        "preferred_assets": ["Northern Trust Custom ESG Index Funds", "VWRL ETF", "Pension Pillars"],
    },
    "GLOBAL": {
        "country_name": "Другие страны / Международный 🌍",
        "currency": "USD",
        "base_fiat_symbol": "$",
        "capital_gains_tax_rate": 0.15,
        "military_tax_rate": 0.0,
        "total_investment_tax_rate": 0.15,
        "dividend_tax_rate": 0.15,
        "recommended_brokers": ["Interactive Brokers", "Saxo Bank", "Swissquote"],
        "tax_notes": "Универсальная международная структура: используйте ирландские аккумулирующие ETF (UCITS) для оптимизации налогов на дивиденды (15% вместо 30%).",
        "preferred_assets": ["VWRA (Vanguard FTSE All-World)", "VUAA (S&P 500 Accumulating)", "High-Yield Cash Reserves"],
    }
}


class CountryEngine:
    @staticmethod
    def get_country_info(country_code: str) -> Dict[str, Any]:
        code = country_code.upper()
        return COUNTRY_CONFIGS.get(code, COUNTRY_CONFIGS["GLOBAL"])

    @staticmethod
    def get_supported_countries() -> List[str]:
        return list(COUNTRY_CONFIGS.keys())

    @staticmethod
    def get_all_countries_list() -> List[Dict[str, Any]]:
        return [
            {
                "code": code,
                "name": data["country_name"],
                "currency": data["currency"],
                "symbol": data["base_fiat_symbol"],
                "tax_rate": data["total_investment_tax_rate"],
            }
            for code, data in COUNTRY_CONFIGS.items()
        ]
